# ********* BEFORE SCRAPPING DYNAMIC WWW **********
# ALWAYS READ _main_address_/robots.txt
# in this file you have instructions what is legal and what's not

from bs4 import BeautifulSoup
import requests

# in this script we use static site, generated by Angela for us, beginners :)
# https://appbrewery.github.io/news.ycombinator.com/
# dynamic site --> https://news.ycombinator.com/news

response = requests.get("https://appbrewery.github.io/news.ycombinator.com/")
# print(response.text) it's basicly the same as with open("site.html"...)...
yc_web_page = response.text

soup = BeautifulSoup(markup=yc_web_page,features="html.parser")
# print(soup.find_all(name="title", recursive=False))

# print('Site title',soup.title.text)
# print('Object type soup.selector()',type(soup.select(selector="a.storylink")))

article_text=[]
article_upvote=[]
article_upvote_imp=[]
article_links=[]
zip_list=[]
for row in soup.find_all(name='a',class_='storylink'):
  article_text.append(row.text)
for row in soup.find_all(name='span', class_="score"):
  article_upvote.append(int((row.text).replace(" ","").replace("points","")))
  article_upvote_imp.append(int((row.text).split()[0]))
for row in soup.find_all(name='a',class_='storylink'):
  article_links.append(row['href'])
for row in zip(article_text,article_upvote_imp,article_links):
  # print(row)
  zip_list.append(row)

theme = zip([row for row in soup.find_all(name='a',class_='storylink')], [row1 for row1 in soup.find_all(name='span', class_="score")])
# print(theme)
# for row in theme:
#   print(row[0].text,row[1].text)
# print(article_upvote_imp)

themes_list = [row for row in soup.select(selector="a.storylink")]
# article_tag = soup.find(name="a",class_="storylink")
# article_text = article_tag.get_text

list1=[]
list2=[]
list3=[]
atag = soup.find_all(name='a', class_='storylink')
for row in atag:
  atext = row.text
  alink = row['href']
  list1.append(atext)
  list2.append(alink)

au = soup.find_all(name='span',class_='score')
for row in au:
  # print(row.getText().split(sep=" ")[0])
  list3.append(int(row.getText().split(sep=" ")[0]))

# print(zip_list[0][1])

# print(list3)
# print(list3.index(max(list3)))

winner = list3.index(max(list3))
print(list1[winner],list2[winner],max(list3))

# print('dlugosc listy list3',len(list3))
# list3.sort(reverse=True)
# print(list3)
# print(help(list3.sort()))